In [5]:
#reading files with open,writing files with open 
f=open("f1.txt","w")
f.write("Hi")
f=open("f1.txt","r")
f.read()
f.close()

In [7]:
#Append()
f=open("f1.txt","w")
f.write("hello")
f=open("f1.txt","a")
#f.append("world")
f=open("f1.txt","r")
f.read()
f.close()

In [8]:
#Reading the files
f=open("f1.txt","w")
f.write("hello world")
f.close()
f=open("f1.txt","r")
f.readline()
f.read(10)
f.close()

In [9]:
#tell() (to know the curser location)
f=open("f1.txt","w")
f.write("hello world")
#f.open("f1.txt","r")
f.tell()
f.close()

In [10]:
#seek() (to change the cursor position)
f=open("f1.txt","w")
f.write("hello world")
f.seek(10,0)
f.close()

In [11]:
#PANDAS 
import pandas as pd
d=[1,2,3]
a=pd.Series(d)
a
b=pd.Series(["hello","hi"])
b

0    hello
1       hi
dtype: object

In [12]:
#Data frame
df={"name":pd.Series([1,2,3]),"rno":pd.Series([0,1,2])}
df=pd.DataFrame(df)
df

name  rno
0     1    0
1     2    1
2     3    2

In [32]:
#Reading data from  the file
a=pd.read_csv("bollywood.csv")
a

SlNo Release Date                    MovieName ReleaseTime      Genre  \
0       1    18-Apr-14                     2 States          LW    Romance   
1       2     4-Jan-13                 Table No. 21           N  Thriller    
2       3    18-Jul-14           Amit Sahni Ki List           N     Comedy   
3       4     4-Jan-13             Rajdhani Express           N     Drama    
4       5     4-Jul-14                 Bobby Jasoos           N     Comedy   
..    ...          ...                          ...         ...        ...   
144   145    27-Feb-15           Dum Laga Ke Haisha           N     Comedy   
145   146    13-Mar-15                         NH10           N   Thriller   
146   147    20-Mar-15  Dilliwali Zaalim Girlfriend           N     Comedy   
147   148    20-Mar-15                     Hunterrr           N     Comedy   
148   149    23-May-14                Kochadaiiyaan          HS     Action   

     Budget  BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes  
0        36               104.00       8576361         26622             2527  
1        10                12.00       1087320          1129              137  
2        10                 4.00        572336           586               54  
3         7                 0.35         42626            86               19  
4        18                10.80       3113427          4512             1224  
..      ...                  ...           ...           ...              ...  
144      15                30.00       3250917          8185              615  
145      13                32.10       5592977         15464             1513  
146      32                12.00       2316047          4289              807  
147       5                11.89       4674795          3706              762  
148     150               120.00       4740727         13466             2649  

[149 rows x 10 columns]

In [35]:
#to retrieve the column in the given data frame
df.columns

Index(['name', 'rno'], dtype='object')

In [36]:
#type(to get the type of the input)
type(df)

pandas.core.frame.DataFrame

In [37]:
#size (to get the size of the data frame)
df.size

6

In [40]:
#shape( to get the shape of the data frame)
df.shape

(3, 2)

In [41]:
#info() ( to get the complete information about the dataframe)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
name    3 non-null int64
rno     3 non-null int64
dtypes: int64(2)
memory usage: 176.0 bytes


In [42]:
#is null()( to get the null values)
df.isnull()

name    rno
0  False  False
1  False  False
2  False  False

In [43]:
#is null().sum() ( to get the no of null values)
df.isnull().sum()

name    0
rno     0
dtype: int64

In [44]:
#head() (to get the first 5 values)
df.head()

name  rno
0     1    0
1     2    1
2     3    2

In [47]:
#tail() to get the last 5 rows
df.tail(1)

name  rno
2     3    2

In [48]:
#describe() ( to get the aggregate values of numerical column)
df.describe()

name  rno
count   3.0  3.0
mean    2.0  1.0
std     1.0  1.0
min     1.0  0.0
25%     1.5  0.5
50%     2.0  1.0
75%     2.5  1.5
max     3.0  2.0

In [51]:
# to get the specific row:

df[0:3]

name  rno
0     1    0
1     2    1
2     3    2

In [52]:
#to get the required columns
df.columns[0:3]

Index(['name', 'rno'], dtype='object')

In [56]:
# to get the single column all values
df["name"]

0    1
1    2
2    3
Name: name, dtype: int64

In [74]:
# iloc[] to get the specified rows and columns
df.iloc[:,:]

name  rno
0     1    0
1     2    1
2     3    2

In [80]:
#to get the random columns:
df.iloc[1:2,[1.2]]

rno
1    1

In [14]:
#working with numpy arrays: numpy 1d arrays,numpy 2d array
# 1-D array
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
#(rows and columns)
a.shape

(3,)

In [16]:
#( to get dimensions of an array)
a.ndim

1

In [17]:
#(to get total number of elements)
a.size

3

In [18]:
#1-D operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)

[-3 -3 -3]


In [19]:
print(a+b)

[5 7 9]


In [20]:
print(a*b)

[ 4 10 18]


In [21]:
#abs() to get the absolute values
a=np.array([1.2,10.3,4])
np.abs(a)

array([ 1.2, 10.3,  4. ])

In [22]:
#sort() to sort the given array in ascending order
a=np.array([50,10,1,4,2])
np.sort(a)

array([ 1,  2,  4, 10, 50])

In [23]:
#to sort in descending order
np.sort(a)[::-1]

array([50, 10,  4,  2,  1])

In [24]:
#ones() to get 1 dimensional ones array
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
#zeros() to get 1 d zeroes array
np.zeros(3)

array([0., 0., 0.])

In [26]:
#aggregate functions
a=np.array([1,2,3,4])
np.sum(a)

10

In [27]:
np.max(a)

4

In [28]:
np.min(a)

1

In [29]:
np.mean(a)

2.5

In [30]:
np.median(a)

2.5

In [31]:
#arange() to arange the given numbers with givenspace
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [32]:
#linspace() to divide the given range into given no of equal parts

a=np.linspace(0,20,3)

In [33]:
#unique() gives the unique numbers in the given array
a=np.array([1,2,1,2])
np.unique(a)

array([1, 2])

In [34]:
#random() to generate random array
np.random.randint(0,10,10)

array([5, 4, 1, 3, 9, 2, 8, 5, 6, 1])

In [35]:
#random.seed() to get the same random values
np.random.seed(7)
np.random.randint(0,10,3)

array([4, 9, 6])

In [36]:
#2-D array

a=np.zeros([3,2])
a


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
a=np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [38]:
np.random.choice([1,3,2],size=(3,2))

array([[1, 3],
       [2, 1],
       [3, 2]])

In [39]:
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.add(a,b)

array([5, 7, 9])

In [1]:
import pandas as pd
d=pd.read_csv("DATA.CSV")
d

NUMBER     NAME DEPT  SALARY GENDER
0       1     PAVI  EEE   30000      F
1       2    PRIYA  CSE   70000      F
2       3   HARSHA   ME   20000      M
3       4  LAVANYA  ECE   32000      F
4       5     RAMA  EEE   40000      F
5       6    BHANU   ME   24000      M
6       7  VARDHAN  EEE   31000      M
7       8  DEEPTHI  CSE   32000      F
8       9    DIVYA  ECE   43000      F
9      10   BHAGYA  CSE   33000      F

In [3]:
d["n1"]=(d["SALARY"]/d["SALARY"].abs().max())

In [4]:
d["n2"]=(d["SALARY"]-d["SALARY"].min())/(d["SALARY"].max()-d["SALARY"].min())

In [5]:
d["n3"]=(d["SALARY"]-d["SALARY"].mean()/d["SALARY"].std())

In [6]:
d

NUMBER     NAME DEPT  SALARY GENDER        n1    n2           n3
0       1     PAVI  EEE   30000      F  0.428571  0.20  29997.43243
1       2    PRIYA  CSE   70000      F  1.000000  1.00  69997.43243
2       3   HARSHA   ME   20000      M  0.285714  0.00  19997.43243
3       4  LAVANYA  ECE   32000      F  0.457143  0.24  31997.43243
4       5     RAMA  EEE   40000      F  0.571429  0.40  39997.43243
5       6    BHANU   ME   24000      M  0.342857  0.08  23997.43243
6       7  VARDHAN  EEE   31000      M  0.442857  0.22  30997.43243
7       8  DEEPTHI  CSE   32000      F  0.457143  0.24  31997.43243
8       9    DIVYA  ECE   43000      F  0.614286  0.46  42997.43243
9      10   BHAGYA  CSE   33000      F  0.471429  0.26  32997.43243